/*
** Retention rules.
*/
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','ARCH_BATCH_ADJUSTMENT_ADDITION',NULL,NULL,'PROCESS_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Archived adjustments (aka refunds) - economic transactions');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','ARCH_BATCH_CHARGE_ADDITION',NULL,NULL,'PROCESS_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Archived charges - economic transactions');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','ARCH_MASTER_CHG_PP_TRANS',NULL,NULL,'REQUEST_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Archived priceplan changes');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','ARCH_MASTER_MEMO_TRANSACTIONS',NULL,NULL,'ENTER_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Archived MEMOs created via Ninja');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','ARCH_NINJA_SUB_CHANGE_STATUS',NULL,NULL,'REQUEST_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Archived subscription status changes (Cancel, Suspend)');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','ARCH_SERVICE_TRANSACTIONS',NULL,NULL,'ENTER_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Archived SOC additions and deletes from Kontant DB');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BAN_ACCT_TYPE_CHANGE',NULL,NULL,'REQUEST_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Change BAN Account Type');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BAN_LEVEL_SOCS_TRX',NULL,NULL,'REQUEST_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Add or Delete BAN level SOC');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BAN_TREE_MEMBER_REMOVAL',NULL,NULL,'REQUEST_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Remove Cancelled BANs from Trees');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_ACTIVATIONS',NULL,NULL,'PROCESS_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Batch activate subscriptions');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_ADDITIONAL_TITLE_UPDATE',NULL,NULL,'REQUEST_DATE',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Batch update Additional Title on BAN');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_ADJUSTMENT_ADDITION',NULL,NULL,'PROCESS_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Adjustments (aka refunds) - economic transactions');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_BAN_BILL_DUE_DAY_UPDATE',NULL,NULL,'PROCESS_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Change billing due days on BANs');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_CHANGE_PRICEPLAN',NULL,NULL,'PROCESS_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Change priceplan + socs on subscriptions');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_CHARGE_ADDITION',NULL,NULL,'PROCESS_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Charges - economic transactions');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_DISCOUNT_ADDITION',NULL,NULL,'PROCESS_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Discount addition to BANs');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_EMAIL_ADDRESS_UPDATE',NULL,NULL,'REQUEST_DATE',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Updates email addresses');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_IMEI_ADDITION',NULL,NULL,'REQUEST_PROCESS_DATE',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Adds IMEI to subscriptions');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_MOVE_SUBSCRIBERS',NULL,NULL,'REQUEST_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Moves subscription to another BAN');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_NAME_ADDRESS_UPDATE',NULL,NULL,'PROCESS_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Update address - all types');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_PRINT_CATEGORY',NULL,NULL,'REQUEST_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Update print category - how the invoices are produced');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_PUBLISHLEVEL_UPDATE',NULL,NULL,'PROCESS_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Update publish level - which data is presented in the white pages');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_SIM_REPLACEMENT',NULL,NULL,'REQUEST_PROCESS_DATE',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Replace SIM');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','CDA_BATCH_ACTIVATIONS',NULL,NULL,'PROCESS_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Batch activations of CDA subscriptions');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','CHG_PRICEPLAN_TRANS',NULL,NULL,'REQUEST_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Change priceplan (old)');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','COOP_MAINTAINANCE_BATCH',NULL,NULL,'REQUESTED_DATE',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Add membership to subscription');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','DSP_REQUEST',NULL,NULL,'PROCESS_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Request a Person ID look-up of BAN');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','GSM_BESTILLING_ARCHIVE',NULL,NULL,'DATO',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Archive of SMSes sent to 1989, such as "FORBRUK"');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','MARKETING_INDICATOR_UPDATE',NULL,NULL,'REQUEST_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Update marketing indicator - how we may contact the customer for further sales, etc.');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','MASTER_CHG_PP_TRANS',NULL,NULL,'REQUEST_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Change priceplan');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','MASTER_MEMO_TRANSACTIONS',NULL,NULL,'REQUEST_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'MEMOs created via Ninja');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','MASTER_TRANSACTIONS',NULL,NULL,'REQUEST_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Add/Delete/Modify SOC');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','MASTER_TRANSACTIONS_XIL',NULL,NULL,'REQUEST_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Old - Recipients of campaigns via XIL');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','MMS_TRANSACTIONS',NULL,NULL,'PROCESS_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Added MMS during migration in 2005');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','NINJA_SUB_CHANGE_STATUS',NULL,NULL,'REQUEST_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Subscription status changes (Cancel, Suspend)');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','NINJA_TIME_PORT',NULL,NULL,'DATE_TIME_PORT',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Port between Telia and SPs (aka Internal Porting)');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','OLDB_MASTER_TRANSACTIONS',NULL,NULL,'REQUEST_STATUS_DATE',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Archived XLDB-changes since 2005');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','RESERVED_NUMBERS',NULL,NULL,'RESERVED_DATE',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Reserved numbers, cleared when released/activated');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','RESERVED_SIM_NUMBERS',NULL,NULL,'RESERVE_DATE',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Mastr of Reserved eSIM numbers - kept for eternity - Important!');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','SALESMAKER_BAN_CREATOR',NULL,NULL,'REQUEST_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Updated BAN info in SalesMaker during June 2009');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','SERVICE_TRANSACTIONS',NULL,NULL,'REQUEST_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'SOC Additions and deletes from Kontant DB');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','SP_PP_ACTIVATIONS',NULL,NULL,'PROCESS_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'SP activations via batch-files between 2005-2008');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','SP_SUBSCRIBER_MOVE',NULL,NULL,'REQUEST_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Sense to Chess migration between 2006-2008');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','TB_PROCESSING_TRANS',NULL,NULL,'REQUEST_TIME',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Change priceplan to TB and add TB SOC');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','TREE_CUG_ADDITION_SUBS',NULL,NULL,'STATUS_DATE',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Addition/deletion of a special CUG soc (GEMMA) on all subscribers in a tree during 2006');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','XLDB_MASTER_TRANSACTIONS',NULL,NULL,'REQUEST_STATUS_DATE',3652,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'XLDB-changes');
/*
** Search rules.
*/
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','ARCH_BATCH_ADJUSTMENT_ADDITION','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Archived adjustments (aka refunds) - economic transactions');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','ARCH_BATCH_CHARGE_ADDITION','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Archived charges - economic transactions');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','ARCH_MASTER_CHG_PP_TRANS','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Archived priceplan changes');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','ARCH_MASTER_MEMO_TRANSACTIONS','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Archived MEMOs created via Ninja');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','ARCH_NINJA_SUB_CHANGE_STATUS','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Archived subscription status changes (Cancel, Suspend)');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','ARCH_SERVICE_TRANSACTIONS','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Archived SOC additions and deletes from Kontant DB');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BAN_ACCT_TYPE_CHANGE','BAN','BAN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Change BAN Account Type');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BAN_LEVEL_SOCS_TRX','BAN','BAN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Add or Delete BAN level SOC');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BAN_TREE_MEMBER_REMOVAL','BAN','BAN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Remove Cancelled BANs from Trees');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_ACTIVATIONS','BAN','BAN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Batch activate subscriptions');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_ACTIVATIONS','CTN','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Batch activate subscriptions');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_ACTIVATIONS','SIM','SIM',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Batch activate subscriptions');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_ADDITIONAL_TITLE_UPDATE','BAN_NO','BAN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Batch update Additional Title on BAN');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_ADDITIONAL_TITLE_UPDATE','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Batch update Additional Title on subscription');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_ADJUSTMENT_ADDITION','BAN_NO','BAN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Adjustments (aka refunds) - economic transactions');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_ADJUSTMENT_ADDITION','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Adjustments (aka refunds) - economic transactions');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_BAN_BILL_DUE_DAY_UPDATE','BAN_NO','BAN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Change billing due days on BANs');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_BAN_BILL_DUE_DAY_UPDATE','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Change billing due days on BANs');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_CHANGE_PRICEPLAN','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Change priceplan + socs on subscriptions');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_CHARGE_ADDITION','BAN_NO','BAN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Charges - economic transactions');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_CHARGE_ADDITION','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Charges - economic transactions');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_DISCOUNT_ADDITION','BAN_NO','BAN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Discount addition to BANs');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_DISCOUNT_ADDITION','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Discount addition to BANs');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_EMAIL_ADDRESS_UPDATE','BAN_NO','BAN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Updates email addresses');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_EMAIL_ADDRESS_UPDATE','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Updates email addresses');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_IMEI_ADDITION','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Adds IMEI to subscriptions');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_MOVE_SUBSCRIBERS','NEW_BAN','BAN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Moves subscription to another BAN');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_MOVE_SUBSCRIBERS','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Moves subscription to another BAN');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_NAME_ADDRESS_UPDATE','BAN_NO','BAN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Update address - all types');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_NAME_ADDRESS_UPDATE','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Update address - all types');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_PRINT_CATEGORY','BAN','BAN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Update print category - how the invoices are produced');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_PUBLISHLEVEL_UPDATE','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Update publish level - which data is presented in the white pages');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_SIM_REPLACEMENT','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Replace SIM');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_SIM_REPLACEMENT','NEW_SIM_NO','SIM',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Replace SIM');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','BATCH_SIM_REPLACEMENT','OLD_SIM_NO','SIM',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Replace SIM');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','CDA_BATCH_ACTIVATIONS','BAN','BAN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Batch activations of CDA subscriptions');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','CDA_BATCH_ACTIVATIONS','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Batch activations of CDA subscriptions');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','CHG_PRICEPLAN_TRANS','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Change priceplan (old)');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','COOP_MAINTAINANCE_BATCH','SUBSCRIBER_NR','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Add membership to subscription');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','DSP_REQUEST','CUSTOMER_ID','BAN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Request a Person ID look-up of BAN');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','GSM_BESTILLING_ARCHIVE','MSISDN','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Archive of SMSes sent to 1989, such as "FORBRUK"');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','MARKETING_INDICATOR_UPDATE','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Update marketing indicator - how we may contact the customer for further sales, etc.');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','MASTER_CHG_PP_TRANS','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Change priceplan');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','MASTER_MEMO_TRANSACTIONS','BAN_NO','BAN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'MEMOs created via Ninja');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','MASTER_MEMO_TRANSACTIONS','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'MEMOs created via Ninja');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','MASTER_TRANSACTIONS','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Add/Delete/Modify SOC');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','MASTER_TRANSACTIONS_XIL','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Old - Recipients of campaigns via XIL');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','MMS_TRANSACTIONS','BAN','BAN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Added MMS during migration in 2005');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','MMS_TRANSACTIONS','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Added MMS during migration in 2005');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','NINJA_SUB_CHANGE_STATUS','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Subscription status changes (Cancel, Suspend)');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','NINJA_TIME_PORT','BAN','BAN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Port between Telia and SPs (aka Internal Porting)');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','NINJA_TIME_PORT','CTN','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Port between Telia and SPs (aka Internal Porting)');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','OLDB_BAN_DETAILS','NEW_BAN','BAN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Archived XLDB-changes since 2005');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','OLDB_MASTER_TRANSACTIONS','BAN','BAN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Archived XLDB-changes since 2005');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','OLDB_MASTER_TRANSACTIONS','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Archived XLDB-changes since 2005');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','RESERVED_NUMBERS','CTN','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Reserved numbers, cleared when released/activated');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','RESERVED_SIM_NUMBERS','SIM_NUMBER','SIM',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Master of Reserved eSIM numbers - kept for eternity - Important!');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','SALESMAKER_BAN_CREATOR','BAN','BAN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Updated BAN info in SalesMaker during June 2009');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','SERVICE_TRANSACTIONS','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'SOC Additions and deletes from Kontant DB');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','SP_PP_ACTIVATIONS','SIM_NO','SIM',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'SP activations via batch-files between 2005-2008');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','SP_PP_ACTIVATIONS','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'SP activations via batch-files between 2005-2008');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','SP_SUBSCRIBER_MOVE','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Sense to Chess migration between 2006-2008');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','SP_SUBSCRIBER_MOVE','TARGET_BAN','BAN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Sense to Chess migration between 2006-2008');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','TB_PROCESSING_TRANS','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Change priceplan to TB and add TB SOC');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','TREE_CUG_ADDITION_SUBS','BAN','BAN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Addition/deletion of a special CUG soc (GEMMA) on all subscribers in a tree during 2006');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','TREE_CUG_ADDITION_SUBS','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'Addition/deletion of a special CUG soc (GEMMA) on all subscribers in a tree during 2006');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','XLDB_BAN_DETAILS','NEW_BAN','BAN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'XLDB-changes');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','XLDB_MASTER_TRANSACTIONS','BAN','BAN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'XLDB-changes');
INSERT INTO gdpr_table_overview
VALUES('NINJADATA','XLDB_MASTER_TRANSACTIONS','SUBSCRIBER_NO','CTN',NULL,NULL,TO_DATE('2018-03-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),'XLDB-changes');

