SELECT a.ban, a.subscriber_no, a.soc, a.effective_date, b.account_type, b.account_sub_type
  FROM service_agreement@fokus a, billing_account@fokus b
  WHERE a.expiration_date > SYSDATE
    AND a.service_type    = 'P' -- 'P'riceplan Soc, 'R'egular Soc
    AND RTRIM(a.soc)     IN ('PPBA', 'PPBB', 'PPBF', 'PPTC', 'PPTF', 'PPTJ', 'PPUA', 'PPUV')
    AND a.ban             = b.ban
    AND b.ban_status      = 'O'
    AND ROWNUM            < 3
 ;
 -- ST: 782661219	GSM04740100831	PPBB     	2015-07-16 00:00	I	FB

Insert into BATCH_CHANGE_PRICEPLAN
(SUBSCRIBER_NO,OLD_PRICEPLAN,NEW_PRICEPLAN,NEW_CAMPAIGN_CODE,NEW_SUBSCRIPTION_TYPE,
 HANDLE_COMMITMENT,SOCS_TO_ADD,SOCS_TO_DELETE,EFFECTIVE_DATE,DEALER,SALES_AGENT,REASON_CODE,
 MEMO_TEXT,WAIVE_FEES,ENTER_TIME,REQUEST_TIME,PROCESS_TIME,PROCESS_STATUS,
 STATUS_DESC,REQUESTOR_ID,SKIP_NINJA_VALIDATION)
values (
 'GSM04792219836','PPUV','PPUR','000000000','PPURREG1',
 'K',NULL,NULL,NULL,'NET','A','KON1',
 'Tester litt','Y',NULL,NULL,NULL,'WAITING',
 NULL,'HGU '||TO_CHAR(SYSDATE,'YYYY-MM-DD'),'N');

Insert into BATCH_CHANGE_PRICEPLAN
(SUBSCRIBER_NO,OLD_PRICEPLAN,NEW_PRICEPLAN,NEW_CAMPAIGN_CODE,NEW_SUBSCRIPTION_TYPE,
 HANDLE_COMMITMENT,SOCS_TO_ADD,SOCS_TO_DELETE,EFFECTIVE_DATE,DEALER,SALES_AGENT,REASON_CODE,
 MEMO_TEXT,WAIVE_FEES,ENTER_TIME,REQUEST_TIME,PROCESS_TIME,PROCESS_STATUS,
 STATUS_DESC,REQUESTOR_ID,SKIP_NINJA_VALIDATION)
values (
 'GSM04792850516','PPUV','PPUR','000000000','PPURREG1',
 'K',NULL,NULL,NULL,'NET','A','KON1',
 'Tester litt','Y',NULL,NULL,NULL,'WAITING',
 'This user had HOMERUN prior to test','HGU '||TO_CHAR(SYSDATE,'YYYY-MM-DD'),'N');


select a.*
  from batch_change_priceplan a
 where a.requestor_id = 'HGU '||TO_CHAR(SYSDATE,'YYYY-MM-DD')
;

select a.SUBSCRIBER_NO, a.OLD_PRICEPLAN, a.NEW_PRICEPLAN, a.NEW_CAMPAIGN_CODE, a.NEW_SUBSCRIPTION_TYPE,
 a.HANDLE_COMMITMENT, a.SOCS_TO_ADD, a.SOCS_TO_DELETE, a.EFFECTIVE_DATE, a.DEALER, a.SALES_AGENT, a.REASON_CODE,
 a.MEMO_TEXT, a.WAIVE_FEES, a.ENTER_TIME, a.REQUEST_TIME, a.PROCESS_TIME, a.PROCESS_STATUS,
 SUBSTR(RTRIM(SUBSTR(a.status_desc, 0, INSTR(a.status_desc || ' [ID', ' [ID'))), INSTR(a.status_desc, ' ') + 1) AS "STATUS_DESC",
 a.REQUESTOR_ID, a.SKIP_NINJA_VALIDATION
  from batch_change_priceplan a
 where a.requestor_id = 'HGU '||TO_CHAR(SYSDATE,'YYYY-MM-DD')
;

