CREATE TABLE "BATCH_TPID_UPDATE" (
  "BAN" NUMBER(9),
  "SUBSCRIBER_NO" VARCHAR2(20 CHAR),
  "LINK_TYPE" CHAR(1 CHAR),
  "TPID" VARCHAR2(50 CHAR),
  "OLD_TPID" VARCHAR2(50 CHAR),
	"ENTER_TIME" DATE,
	"REQUEST_TIME" DATE,
	"REQUEST_ID" VARCHAR2(64 CHAR),
	"PROCESS_TIME" DATE,
	"PROCESS_STATUS" VARCHAR2(15 CHAR) DEFAULT NULL,
	"STATUS_DESC" VARCHAR2(2000 CHAR)
)
;

-------------------------------------------------------
--  Indexxxes
--------------------------------------------------------

CREATE INDEX "BATCH_TPID_UPDATE_IDX1" ON "BATCH_TPID_UPDATE" ("PROCESS_STATUS", "REQUEST_TIME");
CREATE INDEX "BATCH_TPID_UPDATE_IDX2" ON "BATCH_TPID_UPDATE" ("REQUEST_ID", "PROCESS_STATUS");
CREATE INDEX "BATCH_TPID_UPDATE_GDPR" ON "BATCH_TPID_UPDATE" ("PROCESS_TIME");

--------------------------------------------------------
--  Constraints for Table BATCH_CHANGE_PRICEPLAN
--------------------------------------------------------

ALTER TABLE "BATCH_TPID_UPDATE" ADD CONSTRAINT "BATCH_TPID_UPDATE_101" CHECK (process_status IN ('WAITING', 'IN_PROGRESS', 'PRSD_SUCCESS', 'PRSD_ERROR', 'PRSD_PASSED', 'ON_HOLD', 'DUPLICATE')) ENABLE NOVALIDATE;

--------------------------------------------------------
--  DDL for Trigger BATCH_CHANGE_PRICEPLAN_TRG1
--------------------------------------------------------

CREATE OR REPLACE TRIGGER "BATCH_TPID_UPDATE_TRG1"
 BEFORE
  INSERT
 ON BATCH_TPID_UPDATE
REFERENCING NEW AS NEW OLD AS OLD
 FOR EACH ROW
DECLARE
    v_cnt   NUMBER DEFAULT 0;
BEGIN
  IF INSERTING
  THEN
   SELECT sysdate
   INTO :new.enter_time
   FROM dual;

   IF :new.request_time IS NULL
   THEN
    :new.request_time := :new.enter_time;
   END IF;

   IF :new.process_status IS NULL
   THEN
     :new.process_status := 'WAITING';
   END IF;

  END IF;
 END;
/
ALTER TRIGGER "BATCH_TPID_UPDATE_TRG1" ENABLE;

-- Grants for Table
GRANT ALTER ON BATCH_TPID_UPDATE TO ninjamain
/
GRANT DELETE ON BATCH_TPID_UPDATE TO ninjamain
/
GRANT INDEX ON BATCH_TPID_UPDATE TO ninjamain
/
GRANT INSERT ON BATCH_TPID_UPDATE TO ninjamain
/
GRANT SELECT ON BATCH_TPID_UPDATE TO ninjamain
/
GRANT UPDATE ON BATCH_TPID_UPDATE TO ninjamain
/
GRANT REFERENCES ON BATCH_TPID_UPDATE TO ninjamain
/
GRANT ON COMMIT REFRESH ON BATCH_TPID_UPDATE TO ninjamain
/
GRANT QUERY REWRITE ON BATCH_TPID_UPDATE TO ninjamain
/
GRANT DEBUG ON BATCH_TPID_UPDATE TO ninjamain
/
GRANT FLASHBACK ON BATCH_TPID_UPDATE TO ninjamain
/
GRANT ALTER ON BATCH_TPID_UPDATE TO ninjateam
/
GRANT DELETE ON BATCH_TPID_UPDATE TO ninjateam
/
GRANT INDEX ON BATCH_TPID_UPDATE TO ninjateam
/
GRANT INSERT ON BATCH_TPID_UPDATE TO ninjateam
/
GRANT SELECT ON BATCH_TPID_UPDATE TO ninjateam
/
GRANT UPDATE ON BATCH_TPID_UPDATE TO ninjateam
/
GRANT REFERENCES ON BATCH_TPID_UPDATE TO ninjateam
/
GRANT ON COMMIT REFRESH ON BATCH_TPID_UPDATE TO ninjateam
/
GRANT QUERY REWRITE ON BATCH_TPID_UPDATE TO ninjateam
/
GRANT DEBUG ON BATCH_TPID_UPDATE TO ninjateam
/
GRANT FLASHBACK ON BATCH_TPID_UPDATE TO ninjateam
/
