ALTER TABLE "EXTERNAL_CHARGES" DROP CONSTRAINT "EXTERNAL_CHARGES_101";
ALTER TABLE "EXTERNAL_CHARGES" ADD  CONSTRAINT "EXTERNAL_CHARGES_101" CHECK (process_status IN ('NEW', 'PENDING', 'WAITING', 'PRSD_SUCCESS', 'PRSD_ERROR', 'ON_HOLD', 'IN_PROGRESS', 'CANCELLING', 'CANCELLED')) ENABLE NOVALIDATE;
