/*
select 'CREATE OR REPLACE SYNONYM "NINJAMAIN_DK3"."' || a.table_name || '" FOR "' || a.owner || '"."' || a.table_name || '";' as "SYNONYM"
  from all_tables a
 where a.owner = 'NINJARULES_DK3'
   and a.table_name like 'BML%'
order by a.table_name
;
*/

CREATE OR REPLACE SYNONYM "NINJAMAIN_DK3"."BML_ADDITIONAL_PRODUCT_MAPPING" FOR "NINJARULES_DK3"."BML_ADDITIONAL_PRODUCT_MAPPING";
CREATE OR REPLACE SYNONYM "NINJAMAIN_DK3"."BML_BILLING_SYSTEM" FOR "NINJARULES_DK3"."BML_BILLING_SYSTEM";
CREATE OR REPLACE SYNONYM "NINJAMAIN_DK3"."BML_MAIN_PRODUCT_MAPPING" FOR "NINJARULES_DK3"."BML_MAIN_PRODUCT_MAPPING";
