INSERT INTO spm_priceplan_mapping
VALUES('Telio','TELIO_MBB','PVEC',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4100-12-31', 'YYYY-MM-DD'),'Håkan: Added PVEC (Bredbånd Telio Telecom) as TELIO_MBB.');

INSERT INTO spm_priceplan_mapping
VALUES('Telio','NGT_VOICE','PVEE',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4100-12-31', 'YYYY-MM-DD'),'Håkan: Added PVEE (Videreselger NextGenTel) as NGT_VOICE.');

INSERT INTO spm_priceplan_mapping
VALUES('Telio','FWA','PW30',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4100-12-31', 'YYYY-MM-DD'),'Håkan: Added PW30 (Proximo Fixed Wireless Access) as FWA.');

INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_100GB','SPVOL','SPVOL10',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_100GB_RLH_EU','SPVOL','SPVOL10EU',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_100GB_ROD','SPVOL','SPVOL10R',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_10GB','SPVOL','SPVOL04',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_10GB_RLH_EU','SPVOL','SPVOL04EU',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_10GB_RLH_EU_ROD','SPVOL','SPVOL04ER',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_10GB_ROD','SPVOL','SPVOL04R',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_15GB','SPVOL','SPVOL05',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_15GB_RLH_EU','SPVOL','SPVOL05EU',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_15GB_RLH_EU_ROD','SPVOL','SPVOL05ER',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_15GB_ROD','SPVOL','SPVOL05R',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_1GB_RLH_EU','SPVOL','SPVOL01EU',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_1GB_RLH_EU_ROD','SPVOL','SPVOL01ER',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_1GB_ROD','SPVOL','SPVOL01R',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_20GB','SPVOL','SPVOL06',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_20GB_RLH_EU','SPVOL','SPVOL06EU',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_20GB_RLH_EU_ROD','SPVOL','SPVOL06ER',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_20GB_ROD','SPVOL','SPVOL06R',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_25GB','SPVOL','SPVOL07',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_25GB_RLH_EU','SPVOL','SPVOL07EU',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_25GB_RLH_EU_ROD','SPVOL','SPVOL07ER',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_25GB_ROD','SPVOL','SPVOL07R',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_30GB','SPVOL','SPVOL08',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_30GB_RLH_EU','SPVOL','SPVOL08EU',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_30GB_RLH_EU_ROD','SPVOL','SPVOL08ER',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_30GB_ROD','SPVOL','SPVOL08R',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_3GB','SPVOL','SPVOL02',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_3GB_RLH_EU','SPVOL','SPVOL02EU',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_3GB_ROD','SPVOL','SPVOL02R',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_50GB','SPVOL','SPVOL09',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_50GB_RLH_EU','SPVOL','SPVOL09EU',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_50GB_ROD','SPVOL','SPVOL09R',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_5GB','SPVOL','SPVOL03',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_5GB_RLH_EU','SPVOL','SPVOL03EU',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_5GB_RLH_EU_ROD','SPVOL','SPVOL03ER',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_NGT_5GB_ROD','SPVOL','SPVOL03R',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_PROXIMO_05MBPS','SPVOC','SPVOC19',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_PROXIMO_10MBPS','SPVOC','SPVOC20',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_PROXIMO_20MBPS','SPVOC','SPVOC21',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_PROXIMO_30MBPS','SPVOC','SPVOC22',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_PROXIMO_40MBPS','SPVOC','SPVOC23',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_PROXIMO_50MBPS','SPVOC','SPVOC24',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_SHAPING_15GB_40MBPS','DATA_SHAPING2','TUVS10',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_SHAPING_1GB_10MBPS','DATA_SHAPING2','TUVS01',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_SHAPING_1GB_10MBPS_RLH_EU','DATA_SHAPING2','TUVS01EU',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_SHAPING_1GB_40MBPS','DATA_SHAPING2','TUVS02',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_SHAPING_2GB_10MBPS','DATA_SHAPING2','TUVS03',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_SHAPING_2GB_40MBPS','DATA_SHAPING2','TUVS04',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_SHAPING_3GB_10MBPS','DATA_SHAPING2','TUVS05',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_SHAPING_3GB_40MBPS','DATA_SHAPING2','TUVS06',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_SHAPING_5GB_10MBPS','DATA_SHAPING2','TUVS07',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_SHAPING_5GB_10MBPS_RLH_EU','DATA_SHAPING2','TUVS07EU',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_SHAPING_5GB_40MBPS','DATA_SHAPING2','TUVS08',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_SHAPING_8GB_40MBPS','DATA_SHAPING2','TUVS09',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('DATA_XL_PLUS','GPRS','CONV60',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('NGT_DATA_PACK_1','FIXEDPRICE2','SPFAST04',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('NGT_DATA_PACK_2','FIXEDPRICE2','SPFAST05',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('NGT_DATA_PACK_3','FIXEDPRICE2','SPFAST06',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('NGT_DATA_PACK_4','FIXEDPRICE2','SPFAST07',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('NGT_DATA_PACK_5','FIXEDPRICE2','SPFAST08',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('NGT_SPEED_20MBPS','SPQOS','SPQOS02',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('NGT_SPEED_30MBPS','SPQOS','SPQOS03',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('NGT_SPEED_40MBPS','SPQOS','SPQOS04',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('NGT_SPEED_50MBPS','SPQOS','SPQOS05',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('NGT_SPEED_60MBPS','SPQOS','SPQOS06',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
INSERT INTO SPM_SERVICE_MAPPING (SP_CODE,SOC_TYPE,SOC_GROUP,EFFECTIVE_DATE,EXPIRATION_DATE,COMMENTS)
VALUES('VOICEMAIL_MINI','VOICEMAIL','VMMINI',TO_DATE('2020-08-31','YYYY-MM-DD'),TO_DATE('4700-12-31','YYYY-MM-DD'),null);
