SELECT /*+ PARALLEL(SA,4) */
       SA.SUBSCRIBER_NO
--       , 
  FROM SERVICE_AGREEMENT SA, SUBSCRIBER S
 WHERE SA.SUBSCRIBER_NO = S.SUBSCRIBER_NO
   AND SA.BAN           = S.CUSTOMER_ID
   AND S.SUB_STATUS     =  'A' 
   AND SA.SERVICE_TYPE  =  'P' 
   AND SA.SOC        LIKE  'PK%'  
   AND SA.SOC      NOT IN ( 'PKOD' , 'PKOU' )
   AND SA.EXPIRATION_DATE > SYSDATE
   AND     EXISTS (SELECT /*+ PARALLEL(SA1,4) */ 1
                     FROM SERVICE_AGREEMENT SA1 
                    WHERE SA1.BAN = SA.BAN AND SA1.SUBSCRIBER_NO = SA.SUBSCRIBER_NO AND SA1.SOC =  'WDFPRE'  
                      AND SA1.EXPIRATION_DATE > SYSDATE)
   AND NOT EXISTS (SELECT /*+ PARALLEL(SA2,4) */ 1
                     FROM SERVICE_AGREEMENT SA2 
                    WHERE SA2.BAN = SA.BAN AND SA2.SUBSCRIBER_NO = SA.SUBSCRIBER_NO AND (SA2.SOC =  'ODBVMS'  OR SA2.SOC LIKE  'VM%' ) 
                      AND SA2.EXPIRATION_DATE > SYSDATE)                 
   AND     EXISTS (SELECT /*+ PARALLEL(SA3,4) */ 1
                     FROM SERVICE_AGREEMENT SA3 
                    WHERE SA3.BAN = SA.BAN AND SA3.SUBSCRIBER_NO = SA.SUBSCRIBER_NO AND (SA3.SOC LIKE  'CON%'  OR SA3.SOC LIKE  'MPOD%' )
                      AND SA3.EXPIRATION_DATE > SYSDATE)
   AND     EXISTS (SELECT /*+ PARALLEL(SA4,4) */ 1
                     FROM SERVICE_AGREEMENT SA4 
                    WHERE SA4.BAN = SA.BAN AND SA4.SUBSCRIBER_NO = SA.SUBSCRIBER_NO AND SA4.SOC =  'MMS03'  
                      AND SA4.EXPIRATION_DATE > SYSDATE)                     
   AND     ROWNUM < 2001
;