CREATE OR REPLACE PACKAGE NINJAMAIN.MONTHLY_REFILL_HELPER
AS
   PROCEDURE CREATE_MONTHLY_REFILL_RECORDS;
   PROCEDURE TRUNCATE_MONTHLY_REFILL_CHG;
   PROCEDURE RESET_STATUS_TO_WAITING;
   
END; -- Package spec
 
/