CREATE OR REPLACE PACKAGE NINJAMAIN.populate_prepaid_socs AS
    PROCEDURE ADD_WDFPRE_SERVICE;
    PROCEDURE ADD_MPODPRE01_SERVICE;
    PROCEDURE ADD_VMB2CP01_SERVICE;
    PROCEDURE ADD_MMS03_SERVICE;
    PROCEDURE ADD_MMS04_SERVICE;
    PROCEDURE LOG_MESSAGE(procedure_name IN VARCHAR, message IN VARCHAR);
END POPULATE_PREPAID_SOCS;
/