CREATE OR REPLACE PACKAGE NINJAMAIN.populate_np_activities_pack AS
    PROCEDURE POPULATE_NP_BEST_RESEND;
    PROCEDURE POPULATE_PORTING_REMINDER;
    PROCEDURE POPULATE_PORT_IN_ABORT;
    PROCEDURE POPULATE_PORT_OUT_PENALTY;
    PROCEDURE POPULATE_PORT_OUT_CLOSE_CASE;
    PROCEDURE POPULATE_WELCOME_SMS;
    PROCEDURE POPULATE_NP_BEST_RESEND_OLD;
END populate_np_activities_pack ; 
 
/