--
-- NINJAMAIN_PT2
--
DROP DATABASE LINK "NINJAPROD";
CREATE DATABASE LINK "NINJAPROD" CONNECT TO "NINJA" IDENTIFIED BY "NINJA" USING 'P01OL1';

DROP DATABASE LINK "NTCSEL.WORLD";
CREATE DATABASE LINK "NTCSEL.WORLD" CONNECT TO "NTCSEL" IDENTIFIED BY "NTCSEL" USING 'P01OL1';

DROP DATABASE LINK "PROD";
CREATE DATABASE LINK "PROD" CONNECT TO "NTCAPPC_LNG5" IDENTIFIED BY "NTCAPPC_LNG5" USING 'P01OL1';

DROP DATABASE LINK "PROD.WORLD";
CREATE DATABASE LINK "PROD.WORLD" CONNECT TO "NTCAPPC_LNG5" IDENTIFIED BY "NTCAPPC_LNG5" USING 'P01OL1';

--
-- NINJACONFIG_PT2
--
DROP DATABASE LINK "PROD.WORLD";
CREATE DATABASE LINK "PROD.WORLD" CONNECT TO "NTCSEL" IDENTIFIED BY "NTCSEL" USING 'P01OL1';

--
-- NINJADATA_PT2
--
DROP DATABASE LINK "NINJAPROD";
CREATE DATABASE LINK "NINJAPROD" CONNECT TO "NINJA" IDENTIFIED BY "NINJA" USING 'P01OL1';

DROP DATABASE LINK "PROD";
CREATE DATABASE LINK "PROD" CONNECT TO "NTCAPPC_LNG5" IDENTIFIED BY "NTCAPPC_LNG5" USING 'P01OL1';

DROP DATABASE LINK "PROD.WORLD";
CREATE DATABASE LINK "PROD.WORLD" CONNECT TO "NTCSEL" IDENTIFIED BY "NTCSEL" USING 'P01OL1';

--
-- NINJARULES_PT2
--
DROP DATABASE LINK "PROD.WORLD";
CREATE DATABASE LINK "PROD.WORLD" CONNECT TO "NTCSEL" IDENTIFIED BY "NTCSEL" USING 'P01OL1';

--
-- NINJAMAIN_PT
--
DROP DATABASE LINK "NINJAPROD";
CREATE DATABASE LINK "NINJAPROD" CONNECT TO "NINJA" IDENTIFIED BY "NINJA" USING 'P01OL1';

DROP DATABASE LINK "NTCSEL.WORLD";
CREATE DATABASE LINK "NTCSEL.WORLD" CONNECT TO "NTCSEL" IDENTIFIED BY "NTCSEL" USING 'P01OL1';

DROP DATABASE LINK "PROD.WORLD";
CREATE DATABASE LINK "PROD.WORLD" CONNECT TO "NTCAPPC_LNG5" IDENTIFIED BY "NTCAPPC_LNG5" USING 'P01OL1';

--
-- NINJACONFIG_PT
--
DROP DATABASE LINK "PROD.WORLD";
CREATE DATABASE LINK "PROD.WORLD" CONNECT TO "NTCSEL" IDENTIFIED BY "NTCSEL" USING 'P01OL1';

--
-- NINJADATA_PT
--
DROP DATABASE LINK "NINJAPROD";
CREATE DATABASE LINK "NINJAPROD" CONNECT TO "NINJA" IDENTIFIED BY "NINJA" USING 'P01OL1';

DROP DATABASE LINK "PROD";
CREATE DATABASE LINK "PROD" CONNECT TO "NTCAPPC_LNG5" IDENTIFIED BY "NTCAPPC_LNG5" USING 'P01OL1';

DROP DATABASE LINK "PROD.WORLD";
CREATE DATABASE LINK "PROD.WORLD" CONNECT TO "NTCSEL" IDENTIFIED BY "NTCSEL" USING 'P01OL1';

--
-- NINJARULES_PT
--
DROP DATABASE LINK "PROD.WORLD";
CREATE DATABASE LINK "PROD.WORLD" CONNECT TO "NTCSEL" IDENTIFIED BY "NTCSEL" USING 'P01OL1';
