-- execute NINJA_CONFIG_UTILS.POPULATE_DEALER_FOKUS_USER('Z097', 403454, 'A', 'REGULAR' );

DECLARE
  I_DEALER_CODE VARCHAR2(200);
  I_FOKUS_USER NUMBER;
  I_SALES_AGENT VARCHAR2(200);
  I_DEALER_GROUP VARCHAR2(200);
BEGIN
  I_DEALER_CODE := 'Z097';
  I_FOKUS_USER := 403454;
  I_SALES_AGENT := 'A';
  I_DEALER_GROUP := 'REGULAR';

  NINJACONFIG.NINJA_CONFIG_UTILS.POPULATE_DEALER_FOKUS_USER(
    I_DEALER_CODE => I_DEALER_CODE,
    I_FOKUS_USER => I_FOKUS_USER,
    I_SALES_AGENT => I_SALES_AGENT,
    I_DEALER_GROUP => I_DEALER_GROUP
  );
--rollback; 
END;
