SELECT ICIM_AGREEMENT_CODE, ICIM_SUBSCRIPTION_TYPE, ACCOUNT_TYPE,
       ACCOUNT_SUB_TYPE --e, COUNT(*) AS "COUNT"
  FROM ICIM_ORDER_TO_ACCOUNT
 WHERE ICIM_AGREEMENT_CODE = 'BUSINESS.REGULAR.TB'
GROUP BY ICIM_AGREEMENT_CODE, ICIM_SUBSCRIPTION_TYPE, ACCOUNT_TYPE, ACCOUNT_SUB_TYPE
ORDER BY ICIM_AGREEMENT_CODE, ICIM_SUBSCRIPTION_TYPE, ACCOUNT_TYPE, ACCOUNT_SUB_TYPE
;