DECLARE
  I_DEALER_CODE VARCHAR2(200);
  I_FOKUS_USER NUMBER;
  I_SALES_AGENT VARCHAR2(200);
  I_DEALER_GROUP VARCHAR2(200);
BEGIN
  I_DEALER_CODE := NULL;
  I_FOKUS_USER := NULL;
  I_SALES_AGENT := NULL;
  I_DEALER_GROUP := NULL;

  NINJA_CONFIG_UTILS.POPULATE_DEALER_FOKUS_USER(
    I_DEALER_CODE  => 'HE21',
    I_FOKUS_USER   => 402076,
    I_SALES_AGENT  => 'A',
    I_DEALER_GROUP => 'REGULAR'
  );
END;
