/*
**
** This scripts inserts records into NINJATEAM.HGU_TMP_TRANS using the db-link
** from NINJATEAM to WH10P; thus this script needs to be ran as the NINJATEAM
** user.
** We read from a temporary table generated by Staffan Lindberg to get the socs
** to add.
**
*/

/*
** First, add non MMS socs, i.e. MPODPRE01 and VMMINI
*/
INSERT INTO hgu_tmp_trans (SUBSCRIBER_NO, SOC, ACTION, REQUEST_TIME, PRIORITY, REQUEST_ID, MEMO_TEXT)
SELECT "SUBSCRIBER_NO", "SOC", "ACTION", "REQUEST_TIME", "PRIORITY", "REQUEST_ID", "MEMO_TEXT"
  FROM (
    SELECT a.subscriber_no                                          AS "SUBSCRIBER_NO",
           a.soc                                                    AS "SOC",
           'ADD'                                                    AS "ACTION",
           TO_DATE(TO_CHAR(SYSDATE, 'YYYY-MM-DD') || ' 21:10', 'YYYY-MM-DD HH24:MI') AS "REQUEST_TIME",
--           TO_DATE('2012-06-27 21:10', 'YYYY-MM-DD HH24:MI') AS "REQUEST_TIME",
           NULL                                                     AS "PRIORITY", -- Regular priority for non-MMS socs.
           a.request_id || ' ' || TO_CHAR(SYSDATE, 'YYYY-MM-DD')    AS "REQUEST_ID",
           a.memo_text                                              AS "MEMO_TEXT"
      FROM AVD2010.TMP_SLG_CLEA_PREP_20121018@WH10P  a
     WHERE a.soc NOT IN ( 'MMS03' )
)
ORDER BY "SUBSCRIBER_NO"
;

/*
** Second, add MMS socs.
*/
INSERT INTO hgu_tmp_trans (SUBSCRIBER_NO, SOC, ACTION, REQUEST_TIME, PRIORITY, REQUEST_ID, MEMO_TEXT)
SELECT "SUBSCRIBER_NO", "SOC", "ACTION", "REQUEST_TIME", "PRIORITY", "REQUEST_ID", "MEMO_TEXT"
  FROM (
    SELECT a.subscriber_no                                          AS "SUBSCRIBER_NO",
           a.soc                                                    AS "SOC",
           'ADD'                                                    AS "ACTION",
           TO_DATE(TO_CHAR(SYSDATE, 'YYYY-MM-DD') || ' 21:10', 'YYYY-MM-DD HH24:MI') AS "REQUEST_TIME",
--           TO_DATE('2012-06-27 21:10', 'YYYY-MM-DD HH24:MI') AS "REQUEST_TIME",
           a.priority + 1                                           AS "PRIORITY", -- Lower the priority for MMS
           a.request_id || ' ' || TO_CHAR(SYSDATE, 'YYYY-MM-DD')    AS "REQUEST_ID",
           a.memo_text                                              AS "MEMO_TEXT"
      FROM AVD2010.TMP_SLG_CLEA_PREP_20121018@WH10P  a
     WHERE a.soc IN ( 'MMS03' )
)
ORDER BY "SUBSCRIBER_NO"
;

/*
**
** List the contents of the temporary table...
**
*/
SELECT h.soc, NVL(h.priority, 3) AS "PRIORITY", TO_CHAR(h.request_time, 'YYYY-MM-DD HH24:MI') AS "REQUEST_TIME", COUNT(1) AS "COUNT"
  FROM hgu_tmp_trans h
GROUP BY h.soc, NVL(h.priority, 3), TO_CHAR(h.request_time, 'YYYY-MM-DD HH24:MI')
ORDER BY "PRIORITY", h.soc, "REQUEST_TIME"
;

COMMIT WORK
;

/*
-- Look at the number socs in Staffan's table.
SELECT soc, COUNT(1) AS "COUNT"
  FROM AVD2010.TMP_SLG_CLEA_PREP_20121018@WH10P
GROUP BY soc
ORDER BY soc
;

-- Simply look at the first 10 records in Staffan's table.
SELECT a.*
  FROM AVD2010.TMP_SLG_CLEA_PREP_20121018@WH10P  a
WHERE ROWNUM < 11
;
*/


